title: <span style="color:#4e2a84;">Andrew Saab</span>
logo: headshot_circle.png
description: "Postdoctoral Research Fellow<br>Kellogg School of Management"
show_downloads: false
show_github_profile: false
theme: jekyll-theme-minimal
